image: rust:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - cargo fmt --check

lint:
  stage: test
  script:
    - cargo clippy -- -D warnings

test:
  stage: test
  script:
    - cargo test

build:
  stage: build
  script:
    - ./dev/setup.sh
    - (cd app && trunk build --release)
    - cargo build --release --bin server
    # make executable a little smaller. not that important.
    - strip target/release/server
  artifacts:
    paths:
      - target/release/server

pages:
  stage: deploy
  script:
    - mdbook build docs --dest-dir ../public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
