image: rust:latest

format:
  script:
    - cargo fmt --check
  rules:
    # Do not test again after merge
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

lint:
  script:
    - cargo clippy -- -D warnings
  rules:
    # Do not test again after merge
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

test:
  script:
    - cargo test
  rules:
    # Do not test again after merge
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

build:
  script:
    - ./dev/setup.sh
    - (cd app && trunk build --release)
    - cargo build --release --bin server
    # make executable a little smaller. not that important.
    - strip target/release/server
  artifacts:
    paths:
      - target/release/server
  rules:
    # Only create release build on main
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  script:
    - mdbook build docs --dest-dir ../public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # Only deploy pages on main
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
