image: rust:latest

# test

format:
  stage: test
  needs: []
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  script:
    - cargo fmt --check

lint:
  stage: test
  needs: []
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  script:
    - cargo clippy -- -D warnings

test:
  stage: test
  needs: []
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  script:
    - cargo test

# build

pages:
  stage: build
  needs: []
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - ./dev/setup.sh
    - mdbook build docs --dest-dir ../public
  artifacts:
    paths:
      - public

# deploy, triggered by pushing a tag

build-app:
  stage: deploy
  needs: []
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - ./dev/setup.sh
    - cd app
    - trunk build --release
  artifacts:
    paths:
      - app/dist

build-server-x86_64:
  stage: deploy
  needs: [build-app]
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - ./dev/setup.sh
    - TARGET=x86_64-unknown-linux-gnu ./dev/release.sh
    - echo "${CI_JOB_ID}" > job_id_x86_64.txt
  artifacts:
    paths:
      - server-x86_64-unknown-linux-gnu
      - job_id_x86_64.txt

build-server-aarch64:
  stage: deploy
  needs: [build-app]
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - ./dev/setup.sh
    - TARGET=aarch64-unknown-linux-gnu ./dev/release.sh
    - echo "${CI_JOB_ID}" > job_id_aarch64.txt
  artifacts:
    paths:
      - server-aarch64-unknown-linux-gnu
      - job_id_aarch64.txt

release-server-binaries:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: [build-server-x86_64, build-server-aarch64]
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - |
      release-cli create \
        --name "Release $CI_COMMIT_TAG" \
        --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"server-x86_64\", \"filepath\":\"server-x86_64\", \"url\":\"https://gitlab.com/some/repo/-/jobs/`cat job_id_x86_64.txt`/artifacts/download\"}"
        --assets-link "{\"name\":\"server-aarch64\",\"filepath\":\"server-aarch64\",\"url\":\"https://gitlab.com/some/repo/-/jobs/`cat job_id_aarch64.txt`/artifacts/download\"}"
