image: rust:latest

# test

format:
  stage: test
  needs: []
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - cargo fmt --check

lint:
  stage: test
  needs: []
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - cargo clippy -- -D warnings

test:
  stage: test
  needs: []
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - cargo test

# deploy

# Pushes a new tag if version in Cargo.toml is updated.
# Triggers the other deploy jobs to create a release.
try-push-version-tag:
  stage: test
  needs: []
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - ./dev/try_push_version_tag.sh

build:
  stage: deploy
  needs: []
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - ./dev/setup.sh
    - (cd app && trunk build --release)
    - TARGET=aarch64-unknown-linux-gnu ./dev/release.sh
    - TARGET=x86_64-unknown-linux-gnu ./dev/release.sh
    - echo "${CI_JOB_ID}" > job_id.txt
    # controller formware
    - cd controller
    - cargo build --release
    - git clone https://github.com/rej696/elf2uf2.git
    - (cd elf2uf2 ; make build)
    - ./elf2uf2/elf2uf2 target/thumbv6m-none-eabi/release/controller ../controller.uf2
  artifacts:
    paths:
      - server-aarch64-unknown-linux-gnu
      - server-x86_64-unknown-linux-gnu
      - job_id.txt
      - controller.uf2

cut-release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: [build]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "DEBUG {\"name\":\"server_and_controller_builds\",\"url\":\"https://gitlab.switch.ch/hslu/edu/bachelor-engineering-and-architecture/tsm_softweng/tsm_softweng_aut23/3_softeng_zh_2023/3_softeng_zh_2023/-/jobs/$(cat job_id.txt)/artifacts/download\",\"link_type\":\"other\"}"
    - sleep 5 # wait for artifacts to be uploaded, just to be sure
    - |
      release-cli create \
        --name "Release $CI_COMMIT_TAG" \
        --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"server_and_controller_builds\",\"url\":\"https://gitlab.switch.ch/hslu/edu/bachelor-engineering-and-architecture/tsm_softweng/tsm_softweng_aut23/3_softeng_zh_2023/3_softeng_zh_2023/-/jobs/$(cat job_id.txt)/artifacts/download\",\"link_type\":\"other\"}"

# pages

pages:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - ./dev/setup.sh
    - mdbook build docs --dest-dir ../public
  artifacts:
    paths:
      - public
