# configuration options:
# https://github.com/thedodd/trunk/blob/master/Trunk.toml

[serve]
# enable accessing the server from other devices on the network
address = "0.0.0.0"
port = 3000

[watch]
watch = [".", "../models"]

[[proxy]]
backend = "http://localhost:4000/api"

[[proxy]]
backend = "ws://localhost:4000/api/notifications"
ws = true
