[toolchain]
# this nightly version must match the one used by embassy at the git rev we are using as dependency
channel = "nightly-2023-10-02"
targets = [
  "thumbv7em-none-eabi",
  "thumbv7m-none-eabi",
  "thumbv6m-none-eabi",
  "thumbv7em-none-eabihf",
  "thumbv8m.main-none-eabihf",
  "riscv32imac-unknown-none-elf",
  "wasm32-unknown-unknown",
]
components = ["rust-src", "clippy", "rustfmt", "llvm-tools-preview"]
